// 示範資料：故意做成「不對稱」，用來測試缺按鈕、功能條列長短不一的情況
window.CLIENT = {
  客戶名稱: "臺北市政府警察局",
  系統需求: "require Android 4.3 / iOS 11.0 or above",

  APP列表: [
    {
      名稱: "Mobile MDT",
      介紹: "Manage cases everywhere you want.",
      功能: ["Create CASE", "Time event", "Link to RMS"],
      icon: "../img/apps/icon-InfoMDT.png",
      手機圖: "../img/apps/appimg-MobileMDT.png",
      iOS連結: "https://apps.apple.com/example",
      Android連結: "https://example.com/mdt.apk",
      GooglePlay連結: "https://play.google.com/example",
      說明書: "guide-mdt.pdf",
    },
    {
      // 測試：只有 iOS，沒有 Android / Google Play
      名稱: "Active Response",
      介紹: "Respond to incidents in real time.",
      功能: ["Create CASE"],
      icon: "../img/apps/icon-ActiveResponse.png",
      手機圖: "../img/apps/appimg-ActiveResponse.png",
      iOS連結: "https://apps.apple.com/example",
      Android連結: "",
      GooglePlay連結: "",
      說明書: "guide-ar.pdf",
    },
    {
      // 測試：功能條列很長 + 沒有說明書
      名稱: "InfoVNS",
      介紹: "Vehicle and name search on the go.",
      功能: ["Vehicle search", "Person search", "Warrant check", "History log", "Offline cache"],
      icon: "../img/apps/icon-InfoVNS.png",
      手機圖: "../img/apps/appimg-InfoVNS.png",
      iOS連結: "https://apps.apple.com/example",
      Android連結: "https://example.com/vns.apk",
      GooglePlay連結: "",
      說明書: "",
    },
    {
      名稱: "MDT Fire",
      介紹: "Dispatch and response for fire units.",
      功能: ["Dispatch view", "Hydrant map", "Crew status"],
      icon: "../img/apps/icon-MDTFire.png",
      手機圖: "../img/apps/appimg-MDTFire.png",
      iOS連結: "",
      Android連結: "https://example.com/fire.apk",
      GooglePlay連結: "https://play.google.com/example",
      說明書: "guide-fire.pdf",
    },
    {
      名稱: "Personnel",
      介紹: "Manage rosters, shifts and leave.",
      功能: ["Roster", "Shift swap"],
      icon: "../img/apps/icon-Personnel.png",
      手機圖: "../img/apps/appimg-Personnel.png",
      iOS連結: "https://apps.apple.com/example",
      Android連結: "https://example.com/hr.apk",
      GooglePlay連結: "https://play.google.com/example",
      說明書: "guide-hr.pdf",
    },
  ],
};
